### ISSUE TITLE
Issue finding a header file for termios.h

### ISSUE THREAD

**Issue by maxJeon** [arika/ruby-termios#8]
Hi,

I noticed that the source file is missing the termios header file. Can you add back the header
please?
[mkmf.log](https://github.com/arika/ruby-termios/files/5396984/mkmf.log)

**Comment by arika** [comment]
@maxJeon 

Perhaps mingw dosen't support termios.

* https://stackoverflow.com/questions/933745/what-is-the-windows-equivalent-to-the-capabilities-defined-in-sys-select-h-and-t
* https://stackoverflow.com/questions/20772965/where-to-obtain-termios-h

You may use https://rubygems.org/gems/serialport
